FROM tiangolo/nginx-rtmp
FROM php:7.4-cli

COPY nginx.conf /etc/nginx/nginx.conf
COPY autoload.php /www/
COPY database.php /www/
COPY functions.php /www/
COPY index.php /www/
COPY login.php /www/
COPY signup.php /www/
COPY index.html /www/